jobs:
- job: A
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: '8f5d9c09-fe03-4887-968e-f797aa249c7b'  # Replace with your Azure service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "##vso[task.setvariable variable=OUTPUT_VAR;isoutput=true]this is from job A"
    name: passOutput
- job: B
  dependsOn: A
  variables:
    VAR_FROM_JOB_A: $[ dependencies.A.outputs['passOutput.OUTPUT_VAR'] ]  
  steps:
  - script: |
     echo $(VAR_FROM_JOB_A)