jobs:
- job: A_Job
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: '8f5d9c09-fe03-4887-968e-f797aa249c7b'  # Replace with your Azure service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "##vso[task.setvariable variable=outputVar;isoutput=true]this is from job A"
    name: passOutput
- job: B
  dependsOn: A_Job
  variables:
    varFromJobA: $[ dependencies.A_Job.outputs['passOutput.outputVar'] ]  
  steps:
  - script: |
     echo $(varFromJobA)